load("@rules_cc//cc:defs.bzl", "cc_binary")
# cc_binary(
#     name = "map_of_int_to_set_graph",
#     srcs = ["map_of_int_to_set_graph.cc"],
#     deps = ["//src/lib:SolutionLib"],
# )

cc_binary(
    name = "distance_matrix_main",
    srcs = ["distance_matrix_main.cc"],
    deps = ["//src/lib:SolutionLib",
            "//src/lib:graph_distance_matrix_lib"],
)

